### ISSUE TITLE
Assignment 2 is ready for grading

### ISSUE THREAD

**Issue by sivilyslare** [SES-5215-F2020/cschmidt-quant#2]
Assignment 2 is ready for grading in terms of the .html and .rmd files. Thanks!

**Comment by saratepfer** [comment]
Nice job, Christian! A few comments below:

- Rather than calculating the 95% CI by hand, you can instead run a t-test for each of the variables, which will also provide the confidence intervals (and save you some calcs).
- You might consider adjusting the binwidth on some of your histograms. For example, for your marriages variable, it is unlikely that anyone has had non-integer marriages; therefore, you can adjust the binwidth to reflect that (e.g., binwidth = 1). (And that will remove the gaps in your histogram)
