### ISSUE TITLE
Assignment 4 complete! Thanks for grading.

### ISSUE THREAD

**Issue by sivilyslare** [SES-5215-F2020/cschmidt-quant#4]
https://ses-5215-f2020.github.io/cschmidt-quant/cschmidt-quant_assignment4.html

**Comment by saratepfer** [comment]
nice job, Christian! Please see a few comments below.

- line 13: replace {r} with {r, messages = FALSE} to prevent R from printing unnecessary messages associated with loading your packages.
- rather than saying "... than if they were something else," the coefficients should be interpreted relative to the base case. You should be explicit about what that base case is. It's not clear from your assignment what it is. Please specify the base case and make your interpretations of your categorical variables relative to it.
